### ISSUE TITLE
Main page - Dont allow to remove the fist in the row when you has deleted all "opacity-shades" colors from list.

### ISSUE THREAD

**Issue by JulianFloresDev** [fentosv/color-shader#4]
In the main page you have a litle bug which can delete first row, if you want it, because the copy button move fowars.

Before expand to 1024px of width there was no problem:
![image](https://user-images.githubusercontent.com/96196361/199631616-d1225d1b-ea48-4da6-87f2-8193cc227b0d.png)

You could check this media querie to find how fix it: I try removing `width: 70%` property.
![image](https://user-images.githubusercontent.com/96196361/199630880-1e5e51b8-ebd0-450e-81d6-e77cd988af98.png)
![image](https://user-images.githubusercontent.com/96196361/199631321-b7ba53ce-229e-42c3-be1a-b7f66b571548.png)

**Comment by victor-lillo** [comment]
Hello Julian! 

First of all, thanks for reporting the issue.

You were right, when you delete some custom properties and let the longest ones, buttons (delete and copy) were overlapping.  The main problem was not the `width` property (btw, I removed it, looks better now), the problem was absolute positioning the button with a `min-width: fit-content` property in the container.

To resolve this, I just changed the approach of the styles in that component, changing the way I position elements there: absolute changed to flex. 

Check the branch if you want.

Thanks again!
